
# Copyright 2020 Observational Health Data Sciences and Informatics
#
# This file is part of FeatureExtraction
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file has been autogenerated. Do not change by hand.


baseUrl <- Sys.getenv("ohdsiBaseUrl")
library(dplyr)

### Testing functions in WebApi.R

testthat::test_that(desc = "Test .isValidUrl", code = {
  blackhole <- ROhdsiWebApi:::.isValidUrl(urlToCheck = "http://black_hole.net")
  ohdsi <- ROhdsiWebApi:::.isValidUrl(urlToCheck = "https://ohdsi.org/")
  testthat::expect_type(object = blackhole, type = 'logical')
  testthat::expect_type(object = ohdsi, type = 'logical')
  testthat::expect_setequal(object = c(blackhole, ohdsi), expected = c(FALSE, TRUE))
})

testthat::test_that(desc = "Test .checkBaseUrl", code = {
  testthat::skip_if(baseUrl == "")
  value <- ROhdsiWebApi:::.checkBaseUrl(baseUrl = baseUrl)
  testthat::expect_null(value)
})

testthat::test_that(desc = "Test getPriorityVocabulary", code = {
  testthat::skip_if(baseUrl == "")
  value <- ROhdsiWebApi::getPriorityVocabularyKey(baseUrl = baseUrl)
  testthat::expect_type(object = value, type = 'character')
})

testthat::test_that(desc = "Test getWebApiVersion", code = {
  testthat::skip_if(baseUrl == "")
  value <- ROhdsiWebApi::getWebApiVersion(baseUrl = baseUrl)
  testthat::expect_type(object = value, type = 'character')
})

testthat::test_that(desc = "Test getCdmSources", code = {
  testthat::skip_if(baseUrl == "")
  cdmSources <- ROhdsiWebApi::getCdmSources(baseUrl = baseUrl)
  testthat::expect_s3_class(object = cdmSources, class = "data.frame")
  testthat::expect_gt(object = nrow(cdmSources), expected = 0)
})

testthat::test_that(desc = "Test isValidSourceKey", code = {
  testthat::skip_if(baseUrl == "")
  isValid <- ROhdsiWebApi::isValidSourceKey(baseUrl = baseUrl, sourceKeys = 'SYNPUF1K')
  isValid2 <- ROhdsiWebApi::isValidSourceKey(baseUrl = baseUrl, sourceKeys = paste0(sample(letters, size = 10, replace = TRUE), collapse = ""))
  testthat::expect_type(object = isValid, type = 'logical')
  testthat::expect_type(object = isValid2, type = 'logical')
  testthat::expect_setequal(object = c(isValid, isValid2), expected = c(TRUE, FALSE))
})

testthat::test_that(desc = "Test .getStandardCategories", code = {
  standardCategories <- ROhdsiWebApi:::.getStandardCategories() %>% dplyr::arrange() %>% dplyr::pull(categoryStandard)
  testthat::expect_setequal(object = standardCategories, expected = c("conceptSet","cohort","incidenceRate","estimation", "prediction","characterization","pathway"))
})

testthat::test_that(desc = "Test getDefinitionsMetadata", code = {
  testthat::skip_if(baseUrl == "")
  value <- ROhdsiWebApi::getDefinitionsMetadata(baseUrl = baseUrl, category = 'cohort')
  testthat::expect_s3_class(object = value, class = "tbl")
  testthat::expect_s3_class(object = value$createdDate, class = "POSIXct")
})

testthat::test_that(desc = "Test isValidId (negative test)", code = {
  testthat::skip_if(baseUrl == "")
  validId <- ROhdsiWebApi::isValidId(baseUrl = baseUrl, ids = c(0,-1), category = 'cohort')
  testthat::expect_type(object = validId, type = 'logical')
  testthat::expect_setequal(object = validId, expected = c(FALSE, FALSE))
})

testthat::test_that(desc = "Test deleteDefinition (negative test)", code = {
  testthat::skip_if(baseUrl == "")
  testthat::expect_null(object = ROhdsiWebApi::deleteDefinition(baseUrl = baseUrl, id = -1, category = 'cohort'))
})



testthat::test_that("Test getCohortGenerationInformation", {
  testthat::skip_if(baseUrl == "")
  info <- ROhdsiWebApi::getCohortGenerationInformation(1774139, baseUrl = baseUrl)
  testthat::expect_s3_class(info, "data.frame")
  testthat::expect_gt(nrow(info), 0)
})

testthat::test_that("Test getCohortResults", {
  testthat::skip_if(baseUrl == "")
  results <- getCohortResults(1774139, baseUrl = baseUrl)
  testthat::expect_type(results, "list")
  testthat::expect_gt(length(results), 0)
})

testthat::test_that("Test getCohortSql", {
  testthat::skip_if(baseUrl == "")
  cohortDefinition <- getCohortDefinition(cohortId = 1774346, baseUrl = baseUrl)
  sql <- ROhdsiWebApi::getCohortSql(cohortDefinition = cohortDefinition, baseUrl = baseUrl)
  testthat::expect_type(sql, "character")
})

testthat::test_that("Test getDefinitionsMetadata", {
  testthat::skip_if(baseUrl == "")
  categories <- c("conceptSet","cohort","incidenceRate",
                  "estimation","prediction","characterization",
                  "pathway")
  for (category in categories) {
    writeLines(sprintf("Testing category '%s'", category))
    metaData <- ROhdsiWebApi::getDefinitionsMetadata(baseUrl = baseUrl, category = category)
    testthat::expect_s3_class(metaData, "data.frame")
    testthat::expect_gt(nrow(metaData), 0)
  }
})

testthat::test_that("Test isValid...", {
  testthat::skip_if(baseUrl == "")
  categories <- c("conceptSet","cohort","incidenceRate",
                  "estimation","prediction","characterization",
                  "pathway")
  arguments <- list(ids = -1, baseUrl = baseUrl)
  for (category in categories) {
    writeLines(sprintf("Testing category '%s'", category))
    functionName <- paste0("isValid", toupper(substr(category, 1, 1)), substr(category, 2, nchar(category)), "Id")
    names(arguments)[1] <- sprintf("%sIds", category)
    value <- do.call(functionName, arguments)
    testthat::expect_false(value)
  }
})


testthat::test_that("Test evaluate conceptSetExpression (positive test)", {
  testthat::skip_if(baseUrl == "")
  name = paste0("this is a test and may be deleted-", paste0(sample(letters, size = 10, replace = TRUE)))
  expression <- jsonlite::read_json("inst/tests/testthat/json/conceptSetExpression.txt")
  postDefinition1 <- ROhdsiWebApi::postDefinition(name = name, category = 'conceptSet',
                                                           baseUrl = baseUrl, definition = expression)
  postDefinition <- ROhdsiWebApi::postConceptSetDefinition(name = name, 
                                                       baseUrl = baseUrl, conceptSetDefinition = expression)
  testthat::expect_s3_class(object = postDefinition, class = 'tbl')
  conceptSetDefinition <- ROhdsiWebApi::getConceptSetDefinition(conceptSetId = postDefinition$id, baseUrl = baseUrl)
  expressionFromWebApi <- conceptSetDefinition$expression
  testthat::expect_type(object = expressionFromWebApi,type = 'list' )
  testthat::expect_gt(object = length(expressionFromWebApi), expected = 0)
  
  
  resolveConcepts <- ROhdsiWebApi::resolveConceptSet(conceptSetDefinition = conceptSetDefinition, baseUrl = baseUrl)
  testthat::expect_type(object = resolveConcepts, type = 'integer')
  concepts <- ROhdsiWebApi::getConcepts(conceptIds = resolveConcepts, baseUrl = baseUrl)
  testthat::expect_s3_class(object = concepts, class = 'tbl')
  sourceConcepts <- ROhdsiWebApi::getSourceConcepts(conceptIds = resolveConcepts, baseUrl = baseUrl)
  testthat::expect_s3_class(object = concepts, class = 'tbl')
  validTest <- ROhdsiWebApi::isValidConceptSetId(conceptSetIds = postDefinition$id, baseUrl = baseUrl)
  testthat::expect_true(object = validTest)
  })


testthat::test_that("Test postCohortInvokeStop (positive test)", {
  testthat::skip_if(baseUrl == "")
  name = paste0("this is a test and may be deleted-", paste0(sample(letters, size = 10, replace = TRUE)))
  expression <- jsonlite::read_json("inst/tests/testthat/json/cohort.txt")
  postDefinition1 <- ROhdsiWebApi::postDefinition(name = paste0(name, 'd'), category = 'cohort',
                                                       baseUrl = baseUrl, definition = expression)
  testthat::expect_s3_class(object = postDefinition1, class = 'tbl')
  delete <- ROhdsiWebApi::deleteCohortDefinition(cohortId = postDefinition1$id, baseUrl = baseUrl)
  testthat::expect_null(object = delete)
  postDefinition <- ROhdsiWebApi::postCohortDefinition(name = name, 
                                                       baseUrl = baseUrl, cohortDefinition = expression)
  testthat::expect_s3_class(object = postDefinition, class = 'tbl')
  expressionFromWebApi <- ROhdsiWebApi::getCohortDefinition(cohortId = postDefinition$id, baseUrl = baseUrl)$expression
  testthat::expect_type(object = expressionFromWebApi,type = 'list' )
  testthat::expect_gt(object = length(expressionFromWebApi), expected = 0)
  
  invoke <- ROhdsiWebApi::invokeCohortGeneration(cohortId = postDefinition$id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K')
  testthat::expect_s3_class(object = invoke, class = 'tbl')
  testthat::expect_equal(object = invoke$status, expected = c('STARTING') )
  stopGeneration <- ROhdsiWebApi::cancelCohortGeneration(cohortId = postDefinition$id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K' )
  testthat::expect_null(object = stopGeneration)
})


testthat::test_that("Test CharacterizationGetInvokeStop (positive test)", {
  testthat::skip_if(baseUrl == "")
  metadata <- ROhdsiWebApi::getCharacterizationDefinitionsMetaData(baseUrl = baseUrl)
  testthat::expect_s3_class(object = metadata, class = 'tbl')
  id <- metadata %>% dplyr::sample_n(1) %>% dplyr::pull(id)
  
  invoke <- ROhdsiWebApi::invokeCharacterizationGeneration(characterizationId = id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K')
  testthat::expect_s3_class(object = invoke, class = 'tbl')
  testthat::expect_equal(object = invoke$status, expected = c('STARTING') )
  stopGeneration <- ROhdsiWebApi::cancelCharacterizationGeneration(characterizationId = id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K' )
  testthat::expect_null(object = stopGeneration)
})

testthat::test_that("Test PathwayGetInvokeStop (positive test)", {
  testthat::skip_if(baseUrl == "")
  metadata <- ROhdsiWebApi::getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  testthat::expect_s3_class(object = metadata, class = 'tbl')
  id <- metadata %>% dplyr::sample_n(1) %>% dplyr::pull(id)
  
  invoke <- ROhdsiWebApi::invokePathwayGeneration(pathwayId = id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K')
  testthat::expect_s3_class(object = invoke, class = 'tbl')
  testthat::expect_equal(object = invoke$status, expected = c('STARTING') )
  stopGeneration <- ROhdsiWebApi::cancelPathwayGeneration(pathwayId = id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K' )
  testthat::expect_null(object = stopGeneration)
})

testthat::test_that("Test IncidenceRateGetInvokeStop (positive test)", {
  testthat::skip_if(baseUrl == "")
  metadata <- ROhdsiWebApi::getIncidenceRateDefinitionsMetaData(baseUrl = baseUrl)
  testthat::expect_s3_class(object = metadata, class = 'tbl')
  id <- metadata %>% dplyr::sample_n(1) %>% dplyr::pull(id)
  
  invoke <- ROhdsiWebApi::invokeIncidenceRateGeneration(incidenceRateId = id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K')
  testthat::expect_s3_class(object = invoke, class = 'tbl')
  testthat::expect_equal(object = invoke$status, expected = c('STARTING') )
  stopGeneration <- ROhdsiWebApi::cancelIncidenceRateGeneration(incidenceRateId = id, baseUrl = baseUrl, sourceKey = 'SYNPUF1K' )
  testthat::expect_null(object = stopGeneration)
})







#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
#' Get the meta data for Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified 
#' details, hash object, etc. from WebApi for Pathway. This function is useful 
#' to retrieve the current Pathway specifications.  
#'  
#' @template BaseUrl                        
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are
#' returned as text/character.
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl){
  metaData <- getDefinitionsMetadata(baseUrl = baseUrl, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi.
#' \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are 
#' performed. 1) checks if all the ids exists in the WebApi i.e. valid. 
#'  
#' @template BaseUrl
#' @param pathwayIds        A list of integer id(s) of the Pathway to be tested for validity.
#' @return                     A logical vector indicating if an ID is valid.
#' 
#' @examples 
#' \dontrun{
#' isValidPathwayId(pathwayIds = c(13242, 3423, 34), baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
isValidPathwayId <- function(pathwayIds, baseUrl) {
  result <- isValidId(baseUrl = baseUrl, category = 'pathway', ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayDefinition <- function(pathwayId, baseUrl){
  result <- getDefinition(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
  return(result)
}


#' Delete Pathway id definition.
#' \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return               None, unless error.
#' 
#' @examples 
#' \dontrun{
#' deletePathwayDefinition(pathwayId = 13242, baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
deletePathwayDefinition <- function(pathwayId, baseUrl){
  result <- deleteDefinition(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}


#' Check if Pathway definition name exists.
#' \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'  
#' @template BaseUrl
#' @param pathwayName    A string name for the Pathway to be checked.
#' @return                  If found, the function will return a tibble with details of the specification.
#'                          If not found, FALSE will be returned.
#' 
#' @examples 
#' \dontrun{
#' existsPathwayName(pathwayName = 'this text string needs to be checked', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
existsPathwayName <- function(pathwayName, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions.
#' \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve
#' metadata definitions.
#'  
#' @template BaseUrl
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return          FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#' 
#' @examples 
#' \dontrun{
#' detectPathways(pattern = 'this text string to search in pattern', 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
detectPathwaysByName <- function(pattern, negate = FALSE, baseUrl) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(baseUrl = baseUrl)
  matched <- definitionsMetaData %>% 
    dplyr::filter(stringr::str_detect(string = .data$name, pattern = pattern, negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition.
#' \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'  
#' @template BaseUrl
#' @param name           A valid name for the definition. WebApi will use this name (if valid) as
#'                       the name of the definition. WebApi checks for validity,
#'                       such as uniqueness, absence of unacceptable character etc. An error might be thrown.
#' @param PathwayDefinition    An R list object containing the expression for the specification. 
#'                                          This will be converted to JSON expression by function and posted into the WebApi.
#'                                          Note: only limited checks are performed in R to check the validity of this
#'                                          expression.
#' @return            This function will return a dataframe object with one row
#'                    describing the posted WebApi expression and its details.
#'                    If unsuccessful a STOP message will be shown.
#' 
#' @examples 
#' \dontrun{
#' postPathwayDefinition(name = "new valid name", 
#' pathwayDefinition = definition, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
postPathwayDefinition <- function(name, pathwayDefinition, baseUrl){
  result <- postDefinition(name = name, baseUrl = baseUrl, category = 'pathway', definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#' 
#' @examples 
#' \dontrun{
#' getPathwayGenerationInformation(pathwayId = 13242, 
#'                                              baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
getPathwayGenerationInformation <- function(pathwayId, baseUrl){
  .checkBaseUrl(baseUrl)
  response <- getGenerationInformation(id = pathwayId, baseUrl = baseUrl, category = 'pathway')
 return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' invokePathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
invokePathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    invokeGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'  
#' @template BaseUrl
#' @param pathwayId   An integer id representing the id that uniquely identifies a 
#'                       Pathway definition in a WebApi instance.
#' @template SourceKey
#' @return   A tibble with job status information.
#' 
#' @examples 
#' \dontrun{
#' cancelPathwayGeneration(pathwayId = 13242, 
#' baseUrl = "http://server.org:80/WebAPI",
#' sourceKey = 'HCUP')
#' }
#' @export
cancelPathwayGeneration <- function(pathwayId, baseUrl, sourceKey){
  .checkBaseUrl(baseUrl)
  response <-
    cancelGeneration(
      id = pathwayId,
      baseUrl = baseUrl,
      category = 'pathway',
      sourceKey = sourceKey
    )
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'  
#' @template BaseUrl
#' @template PathwayId
#' @return            An R object with results.
#' 
#' @examples 
#' \dontrun{
#' getPathwayResults(pathwayId = 342, 
#' baseUrl = "http://server.org:80/WebAPI")
#' }
#' @export
# Check name
getPathwayResults <- function(pathwayId, baseUrl) {
  result <- getResults(baseUrl = baseUrl, id = pathwayId, category = 'pathway')
  return(result)
}
