# Copyright 2020 Observational Health Data Sciences and Informatics
#
# This file is part of FeatureExtraction
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file has been autogenerated. Do not change by hand.



  
#' Retrieve the meta data for ConceptSet definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for ConceptSet. This function is useful to retrieve the current ConceptSet
#' specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for ConceptSet. Note: modifiedDate and createdDate are returned
#' as text/character.
#'
#' @examples
#' getConceptSetDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getConceptSetDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("conceptSet")))
}


#' Check if ConceptSet id is valid.
#'
#' @details
#' Checks if a set of id for a ConceptSet is valid, i.e. checks if all the ids exists in the WebApi
#' i.e. valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the ConceptSet to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidConceptSetId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidConceptSetId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("conceptSet"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
#' Retrieve the meta data for Cohort definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for Cohort. This function is useful to retrieve the current Cohort
#' specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for Cohort. Note: modifiedDate and createdDate are returned as
#' text/character.
#'
#' @examples
#' getCohortDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getCohortDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("cohort")))
}


#' Check if Cohort id is valid.
#'
#' @details
#' Checks if a set of id for a Cohort is valid, i.e. checks if all the ids exists in the WebApi i.e.
#' valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the Cohort to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidCohortId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidCohortId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("cohort"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
#' Retrieve the meta data for IncidenceRate definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for IncidenceRate. This function is useful to retrieve the current
#' IncidenceRate specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for IncidenceRate. Note: modifiedDate and createdDate are
#' returned as text/character.
#'
#' @examples
#' getIncidenceRateDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getIncidenceRateDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("incidenceRate")))
}


#' Check if IncidenceRate id is valid.
#'
#' @details
#' Checks if a set of id for a IncidenceRate is valid, i.e. checks if all the ids exists in the WebApi
#' i.e. valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the IncidenceRate to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidIncidenceRateId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidIncidenceRateId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("incidenceRate"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
#' Retrieve the meta data for Estimation definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for Estimation. This function is useful to retrieve the current Estimation
#' specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for Estimation. Note: modifiedDate and createdDate are returned
#' as text/character.
#'
#' @examples
#' getEstimationDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getEstimationDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("estimation")))
}


#' Check if Estimation id is valid.
#'
#' @details
#' Checks if a set of id for a Estimation is valid, i.e. checks if all the ids exists in the WebApi
#' i.e. valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the Estimation to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidEstimationId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidEstimationId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("estimation"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
#' Retrieve the meta data for Prediction definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for Prediction. This function is useful to retrieve the current Prediction
#' specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for Prediction. Note: modifiedDate and createdDate are returned
#' as text/character.
#'
#' @examples
#' getPredictionDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getPredictionDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("prediction")))
}


#' Check if Prediction id is valid.
#'
#' @details
#' Checks if a set of id for a Prediction is valid, i.e. checks if all the ids exists in the WebApi
#' i.e. valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the Prediction to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidPredictionId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidPredictionId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("prediction"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
#' Retrieve the meta data for Characterization definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for Characterization. This function is useful to retrieve the current
#' Characterization specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for Characterization. Note: modifiedDate and createdDate are
#' returned as text/character.
#'
#' @examples
#' getCharacterizationDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getCharacterizationDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("characterization")))
}


#' Check if Characterization id is valid.
#'
#' @details
#' Checks if a set of id for a Characterization is valid, i.e. checks if all the ids exists in the
#' WebApi i.e. valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the Characterization to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidCharacterizationId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidCharacterizationId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("characterization"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
#' Retrieve the meta data for Pathway definitions.
#'
#' @details
#' Obtains the meta data of WebApi specifications such as id, name, created/modified details, hash
#' object, etc. from WebApi for Pathway. This function is useful to retrieve the current Pathway
#' specifications.
#'
#' @template BaseUrl
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are returned as
#' text/character.
#'
#' @examples
#' getPathwayDefinitionsMetaData(baseUrl = "http://server.org:80/WebAPI")
#'
#' @export
getPathwayDefinitionsMetaData <- function(baseUrl) {
  .checkBaseUrl(baseUrl)
  return(getWebApiMetadata(baseUrl = baseUrl, categories = c("pathway")))
}


#' Check if Pathway id is valid.
#'
#' @details
#' Checks if a set of id for a Pathway is valid, i.e. checks if all the ids exists in the WebApi i.e.
#' valid.
#'
#' @template BaseUrl
#' @param    ids       A list of integer id(s) of the Pathway to be tested for validity.
#' @param    verbose   Do you want to know what ids are invalid? This parameter will return list of
#'                     integers representing invalid ids. Default = FALSE
#' @return
#' Function will return TRUE if all ids in the set are valid. Function will return FALSE if any id is
#' not valid. Optionally, specify = TRUE will return a list of ids that are no valid.
#'
#' @examples
#' isValidPathwayId(baseUrl = "http://server.org:80/WebAPI", ids = c(13242, 3423, 34))
#'
#' @export
isValidPathwayId <- function(baseUrl, ids, verbose = FALSE) {
  .checkBaseUrl(baseUrl)

  errorMessage <- checkmate::makeAssertCollection()
  checkmate::assertIntegerish(ids, add = errorMessage)
  checkmate::assertLogical(verbose, add = errorMessage)
  checkmate::reportAssertions(errorMessage)

  validIds <- getWebApiMetadata(baseUrl = baseUrl, categories = c("pathway"))

  invalidIds <- tidyr::tibble(id = ids) %>% dplyr::anti_join(y = validIds, by = c(id = "id"))


  if (nrow(invalidIds) > 0) {
    if (verbose == TRUE) {
      return(invalidIds %>% dplyr::select(id) %>% dplyr::distinct() %>% dplyr::pull())
    } else {
      return(FALSE)
    }
  } else {
    return(TRUE)
  }
}
