# Copyright 2020 Observational Health Data Sciences and Informatics
#
# This file is part of FeatureExtraction
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.


# This file has been autogenerated. Do not change by hand.


#' Get the meta data for ConceptSet definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for ConceptSet. This function is useful to retrieve the current ConceptSet
#' specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for ConceptSet. Note: modifiedDate and createdDate are returned
#' as text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getConceptSetDefinitionsMetaData(wc)
#' }
#' @export
getConceptSetDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("conceptSet"))
  return(metaData)
}


#' is ConceptSet id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a ConceptSet is valid. The following checks are performed. 1) checks if
#' all the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param conceptSetIds   A list of integer id(s) of the ConceptSet to be tested for validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidConceptSetId(wc, conceptSetIds = c(13242, 3423, 34))
#' }
#' @export
isValidConceptSetId <- function(wc, conceptSetIds) {
  result <- isValidId(wc = wc, category = "conceptSet", ids = conceptSetIds)
  return(result)
}


#' Get ConceptSet id definition. \lifecycle{stable}
#' @details
#' Obtain the ConceptSet definition from WebAPI for a given ConceptSet id
#'
#' @template WebApiConnection
#' @param conceptSetId   An integer id representing the id that uniquely identifies a ConceptSet
#'                       definition in a WebApi instance.
#' @return
#' An R object representing the ConceptSet definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getConceptSetDefinition(wc, conceptSetId = 13242)
#' }
#' @export
getConceptSetDefinition <- function(wc, conceptSetId) {
  result <- getDefinition(wc = wc, id = conceptSetId, category = "conceptSet")
  return(result)
}


#' Delete ConceptSet id definition. \lifecycle{stable}
#' @details
#' Delete the ConceptSet definition from WebAPI for a given ConceptSet id
#'
#' @template WebApiConnection
#' @param conceptSetId   An integer id representing the id that uniquely identifies a ConceptSet
#'                       definition in a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deleteConceptSetDefinition(wc, conceptSetId = 13242)
#' }
#' @export
deleteConceptSetDefinition <- function(wc, conceptSetId) {
  result <- deleteDefinition(wc = wc, id = conceptSetId, category = "conceptSet")
  return(result)
}


#' Check if ConceptSet definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a ConceptSet definition name.
#'
#' @template WebApiConnection
#' @param conceptSetName   A string name for the ConceptSet to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsConceptSetName(wc, conceptSetName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsConceptSetName <- function(wc, conceptSetName) {
  definitionsMetaData <- getConceptSetDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == conceptSetName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched ConceptSet definitions. \lifecycle{stable}
#' @details
#' Detect string matched ConceptSet definition names from the WebApi, and retrieve metadata
#' definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getConceptSetDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectConceptSets(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectConceptSetsByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getConceptSetDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post ConceptSet definition. \lifecycle{maturing}
#' @details
#' Post ConceptSet definition to WebAPI
#'
#' @template WebApiConnection
#' @param name                   A valid name for the definition. WebApi will use this name (if valid)
#'                               as the name of the definition. WebApi checks for validity, such as
#'                               uniqueness, absence of unacceptable character etc. An error might be
#'                               thrown.
#' @param conceptSetDefinition   An R list object containing the expression for the specification. This
#'                               will be converted to JSON expression by function and posted into the
#'                               WebApi. Note: only limited checks are performed in R to check the
#'                               validity of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postConceptSetDefinition(wc, name = "new valid name", conceptSetDefinition = definition)
#' }
#' @export
postConceptSetDefinition <- function(wc, name, conceptSetDefinition) {
  result <- postDefinition(wc,
                           name = name,
                           category = "conceptSet",
                           definition = conceptSetDefinition)
  return(result)
}
#' Get the meta data for Cohort definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for Cohort. This function is useful to retrieve the current Cohort specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for Cohort. Note: modifiedDate and createdDate are returned as
#' text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCohortDefinitionsMetaData(wc)
#' }
#' @export
getCohortDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("cohort"))
  return(metaData)
}


#' is Cohort id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a Cohort is valid. The following checks are performed. 1) checks if all
#' the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param cohortIds   A list of integer id(s) of the Cohort to be tested for validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidCohortId(wc, cohortIds = c(13242, 3423, 34))
#' }
#' @export
isValidCohortId <- function(wc, cohortIds) {
  result <- isValidId(wc = wc, category = "cohort", ids = cohortIds)
  return(result)
}


#' Get Cohort id definition. \lifecycle{stable}
#' @details
#' Obtain the Cohort definition from WebAPI for a given Cohort id
#'
#' @template WebApiConnection
#' @param cohortId   An integer id representing the id that uniquely identifies a Cohort definition in
#'                   a WebApi instance.
#' @return
#' An R object representing the Cohort definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCohortDefinition(wc, cohortId = 13242)
#' }
#' @export
getCohortDefinition <- function(wc, cohortId) {
  result <- getDefinition(wc = wc, id = cohortId, category = "cohort")
  return(result)
}


#' Delete Cohort id definition. \lifecycle{stable}
#' @details
#' Delete the Cohort definition from WebAPI for a given Cohort id
#'
#' @template WebApiConnection
#' @param cohortId   An integer id representing the id that uniquely identifies a Cohort definition in
#'                   a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deleteCohortDefinition(wc, cohortId = 13242)
#' }
#' @export
deleteCohortDefinition <- function(wc, cohortId) {
  result <- deleteDefinition(wc = wc, id = cohortId, category = "cohort")
  return(result)
}


#' Check if Cohort definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Cohort definition name.
#'
#' @template WebApiConnection
#' @param cohortName   A string name for the Cohort to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsCohortName(wc, cohortName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsCohortName <- function(wc, cohortName) {
  definitionsMetaData <- getCohortDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == cohortName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Cohort definitions. \lifecycle{stable}
#' @details
#' Detect string matched Cohort definition names from the WebApi, and retrieve metadata definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getCohortDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectCohorts(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectCohortsByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getCohortDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Cohort definition. \lifecycle{maturing}
#' @details
#' Post Cohort definition to WebAPI
#'
#' @template WebApiConnection
#' @param name               A valid name for the definition. WebApi will use this name (if valid) as
#'                           the name of the definition. WebApi checks for validity, such as
#'                           uniqueness, absence of unacceptable character etc. An error might be
#'                           thrown.
#' @param cohortDefinition   An R list object containing the expression for the specification. This
#'                           will be converted to JSON expression by function and posted into the
#'                           WebApi. Note: only limited checks are performed in R to check the validity
#'                           of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postCohortDefinition(wc, name = "new valid name", cohortDefinition = definition)
#' }
#' @export
postCohortDefinition <- function(wc, name, cohortDefinition) {
  result <- postDefinition(wc, name = name, category = "cohort", definition = cohortDefinition)
  return(result)
}

#' Get generation information for Cohort id.
#'
#' @details
#' Get generation (execution) information about Cohort for a cohortId.
#'
#' @template WebApiConnection
#' @param cohortId   An integer id representing the id that uniquely identifies a Cohort definition in
#'                   a WebApi instance.
#' @return
#' An R object representing the Cohort definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCohortGenerationInformation(wc, cohortId = 13242)
#' }
#' @export
getCohortGenerationInformation <- function(wc, cohortId) {
  .checkBaseUrl(wc$baseUrl)
  response <- getGenerationInformation(wc = wc, id = cohortId, category = "cohort")
  return(response)
}


#' Invoke generation of Cohort id.
#'
#' @details
#' Invoke the generation of Cohort id in the WebApi.
#'
#' @template WebApiConnection
#' @param cohortId   An integer id representing the id that uniquely identifies a Cohort definition in
#'                   a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' invokeCohortGeneration(wc, cohortId = 13242, sourceKey = "HCUP")
#' }
#' @export
invokeCohortGeneration <- function(wc, cohortId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- invokeGeneration(wc, id = cohortId, category = "cohort", sourceKey = sourceKey)
  return(response)
}

#' Cancel generation of Cohort id.
#'
#' @details
#' Cancel the generation of Cohort id in the WebApi.
#'
#' @template WebApiConnection
#' @param cohortId   An integer id representing the id that uniquely identifies a Cohort definition in
#'                   a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' cancelCohortGeneration(wc, cohortId = 13242, sourceKey = "HCUP")
#' }
#' @export
cancelCohortGeneration <- function(wc, cohortId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- cancelGeneration(wc, id = cohortId, category = "cohort", sourceKey = sourceKey)
  return(response)
}


#' Get results for a Cohort Id.
#'
#' @details
#' Get the results for Cohort id.
#'
#' @template WebApiConnection
#' @template CohortId
#' @return
#' An R object with results.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCohortResults(wc, cohortId = 342)
#' }
#' @export
# Check name
getCohortResults <- function(wc, cohortId) {
  result <- getResults(wc = wc, id = cohortId, category = "cohort")
  return(result)
}
#' Get the meta data for IncidenceRate definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for IncidenceRate. This function is useful to retrieve the current IncidenceRate
#' specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for IncidenceRate. Note: modifiedDate and createdDate are
#' returned as text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getIncidenceRateDefinitionsMetaData(wc)
#' }
#' @export
getIncidenceRateDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("incidenceRate"))
  return(metaData)
}


#' is IncidenceRate id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a IncidenceRate is valid. The following checks are performed. 1) checks
#' if all the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param incidenceRateIds   A list of integer id(s) of the IncidenceRate to be tested for validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidIncidenceRateId(wc, incidenceRateIds = c(13242, 3423, 34))
#' }
#' @export
isValidIncidenceRateId <- function(wc, incidenceRateIds) {
  result <- isValidId(wc = wc, category = "incidenceRate", ids = incidenceRateIds)
  return(result)
}


#' Get IncidenceRate id definition. \lifecycle{stable}
#' @details
#' Obtain the IncidenceRate definition from WebAPI for a given IncidenceRate id
#'
#' @template WebApiConnection
#' @param incidenceRateId   An integer id representing the id that uniquely identifies a IncidenceRate
#'                          definition in a WebApi instance.
#' @return
#' An R object representing the IncidenceRate definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getIncidenceRateDefinition(wc, incidenceRateId = 13242)
#' }
#' @export
getIncidenceRateDefinition <- function(wc, incidenceRateId) {
  result <- getDefinition(wc = wc, id = incidenceRateId, category = "incidenceRate")
  return(result)
}


#' Delete IncidenceRate id definition. \lifecycle{stable}
#' @details
#' Delete the IncidenceRate definition from WebAPI for a given IncidenceRate id
#'
#' @template WebApiConnection
#' @param incidenceRateId   An integer id representing the id that uniquely identifies a IncidenceRate
#'                          definition in a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deleteIncidenceRateDefinition(wc, incidenceRateId = 13242)
#' }
#' @export
deleteIncidenceRateDefinition <- function(wc, incidenceRateId) {
  result <- deleteDefinition(wc = wc, id = incidenceRateId, category = "incidenceRate")
  return(result)
}


#' Check if IncidenceRate definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a IncidenceRate definition name.
#'
#' @template WebApiConnection
#' @param incidenceRateName   A string name for the IncidenceRate to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsIncidenceRateName(wc, incidenceRateName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsIncidenceRateName <- function(wc, incidenceRateName) {
  definitionsMetaData <- getIncidenceRateDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == incidenceRateName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched IncidenceRate definitions. \lifecycle{stable}
#' @details
#' Detect string matched IncidenceRate definition names from the WebApi, and retrieve metadata
#' definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from
#' \link[ROhdsiWebApi]{getIncidenceRateDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectIncidenceRates(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectIncidenceRatesByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getIncidenceRateDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post IncidenceRate definition. \lifecycle{maturing}
#' @details
#' Post IncidenceRate definition to WebAPI
#'
#' @template WebApiConnection
#' @param name                      A valid name for the definition. WebApi will use this name (if
#'                                  valid) as the name of the definition. WebApi checks for validity,
#'                                  such as uniqueness, absence of unacceptable character etc. An error
#'                                  might be thrown.
#' @param incidenceRateDefinition   An R list object containing the expression for the specification.
#'                                  This will be converted to JSON expression by function and posted
#'                                  into the WebApi. Note: only limited checks are performed in R to
#'                                  check the validity of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postIncidenceRateDefinition(wc, name = "new valid name", incidenceRateDefinition = definition)
#' }
#' @export
postIncidenceRateDefinition <- function(wc, name, incidenceRateDefinition) {
  result <- postDefinition(wc,
                           name = name,
                           category = "incidenceRate",
                           definition = incidenceRateDefinition)
  return(result)
}

#' Get generation information for IncidenceRate id.
#'
#' @details
#' Get generation (execution) information about IncidenceRate for a incidenceRateId.
#'
#' @template WebApiConnection
#' @param incidenceRateId   An integer id representing the id that uniquely identifies a IncidenceRate
#'                          definition in a WebApi instance.
#' @return
#' An R object representing the IncidenceRate definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getIncidenceRateGenerationInformation(wc, incidenceRateId = 13242)
#' }
#' @export
getIncidenceRateGenerationInformation <- function(wc, incidenceRateId) {
  .checkBaseUrl(wc$baseUrl)
  response <- getGenerationInformation(wc = wc, id = incidenceRateId, category = "incidenceRate")
  return(response)
}


#' Invoke generation of IncidenceRate id.
#'
#' @details
#' Invoke the generation of IncidenceRate id in the WebApi.
#'
#' @template WebApiConnection
#' @param incidenceRateId   An integer id representing the id that uniquely identifies a IncidenceRate
#'                          definition in a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' invokeIncidenceRateGeneration(wc, incidenceRateId = 13242, sourceKey = "HCUP")
#' }
#' @export
invokeIncidenceRateGeneration <- function(wc, incidenceRateId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- invokeGeneration(wc,
                               id = incidenceRateId,
                               category = "incidenceRate",
                               sourceKey = sourceKey)
  return(response)
}

#' Cancel generation of IncidenceRate id.
#'
#' @details
#' Cancel the generation of IncidenceRate id in the WebApi.
#'
#' @template WebApiConnection
#' @param incidenceRateId   An integer id representing the id that uniquely identifies a IncidenceRate
#'                          definition in a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' cancelIncidenceRateGeneration(wc, incidenceRateId = 13242, sourceKey = "HCUP")
#' }
#' @export
cancelIncidenceRateGeneration <- function(wc, incidenceRateId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- cancelGeneration(wc,
                               id = incidenceRateId,
                               category = "incidenceRate",
                               sourceKey = sourceKey)
  return(response)
}


#' Get results for a IncidenceRate Id.
#'
#' @details
#' Get the results for IncidenceRate id.
#'
#' @template WebApiConnection
#' @template IncidenceRateId
#' @return
#' An R object with results.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getIncidenceRateResults(wc, incidenceRateId = 342)
#' }
#' @export
# Check name
getIncidenceRateResults <- function(wc, incidenceRateId) {
  result <- getResults(wc = wc, id = incidenceRateId, category = "incidenceRate")
  return(result)
}
#' Get the meta data for Estimation definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for Estimation. This function is useful to retrieve the current Estimation
#' specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for Estimation. Note: modifiedDate and createdDate are returned
#' as text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getEstimationDefinitionsMetaData(wc)
#' }
#' @export
getEstimationDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("estimation"))
  return(metaData)
}


#' is Estimation id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a Estimation is valid. The following checks are performed. 1) checks if
#' all the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param estimationIds   A list of integer id(s) of the Estimation to be tested for validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidEstimationId(wc, estimationIds = c(13242, 3423, 34))
#' }
#' @export
isValidEstimationId <- function(wc, estimationIds) {
  result <- isValidId(wc = wc, category = "estimation", ids = estimationIds)
  return(result)
}


#' Get Estimation id definition. \lifecycle{stable}
#' @details
#' Obtain the Estimation definition from WebAPI for a given Estimation id
#'
#' @template WebApiConnection
#' @param estimationId   An integer id representing the id that uniquely identifies a Estimation
#'                       definition in a WebApi instance.
#' @return
#' An R object representing the Estimation definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getEstimationDefinition(wc, estimationId = 13242)
#' }
#' @export
getEstimationDefinition <- function(wc, estimationId) {
  result <- getDefinition(wc = wc, id = estimationId, category = "estimation")
  return(result)
}


#' Delete Estimation id definition. \lifecycle{stable}
#' @details
#' Delete the Estimation definition from WebAPI for a given Estimation id
#'
#' @template WebApiConnection
#' @param estimationId   An integer id representing the id that uniquely identifies a Estimation
#'                       definition in a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deleteEstimationDefinition(wc, estimationId = 13242)
#' }
#' @export
deleteEstimationDefinition <- function(wc, estimationId) {
  result <- deleteDefinition(wc = wc, id = estimationId, category = "estimation")
  return(result)
}


#' Check if Estimation definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Estimation definition name.
#'
#' @template WebApiConnection
#' @param estimationName   A string name for the Estimation to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsEstimationName(wc, estimationName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsEstimationName <- function(wc, estimationName) {
  definitionsMetaData <- getEstimationDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == estimationName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Estimation definitions. \lifecycle{stable}
#' @details
#' Detect string matched Estimation definition names from the WebApi, and retrieve metadata
#' definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getEstimationDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectEstimations(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectEstimationsByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getEstimationDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Estimation definition. \lifecycle{maturing}
#' @details
#' Post Estimation definition to WebAPI
#'
#' @template WebApiConnection
#' @param name                   A valid name for the definition. WebApi will use this name (if valid)
#'                               as the name of the definition. WebApi checks for validity, such as
#'                               uniqueness, absence of unacceptable character etc. An error might be
#'                               thrown.
#' @param estimationDefinition   An R list object containing the expression for the specification. This
#'                               will be converted to JSON expression by function and posted into the
#'                               WebApi. Note: only limited checks are performed in R to check the
#'                               validity of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postEstimationDefinition(wc, name = "new valid name", estimationDefinition = definition)
#' }
#' @export
postEstimationDefinition <- function(wc, name, estimationDefinition) {
  result <- postDefinition(wc,
                           name = name,
                           category = "estimation",
                           definition = estimationDefinition)
  return(result)
}
#' Get the meta data for Prediction definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for Prediction. This function is useful to retrieve the current Prediction
#' specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for Prediction. Note: modifiedDate and createdDate are returned
#' as text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getPredictionDefinitionsMetaData(wc)
#' }
#' @export
getPredictionDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("prediction"))
  return(metaData)
}


#' is Prediction id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a Prediction is valid. The following checks are performed. 1) checks if
#' all the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param predictionIds   A list of integer id(s) of the Prediction to be tested for validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidPredictionId(wc, predictionIds = c(13242, 3423, 34))
#' }
#' @export
isValidPredictionId <- function(wc, predictionIds) {
  result <- isValidId(wc = wc, category = "prediction", ids = predictionIds)
  return(result)
}


#' Get Prediction id definition. \lifecycle{stable}
#' @details
#' Obtain the Prediction definition from WebAPI for a given Prediction id
#'
#' @template WebApiConnection
#' @param predictionId   An integer id representing the id that uniquely identifies a Prediction
#'                       definition in a WebApi instance.
#' @return
#' An R object representing the Prediction definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getPredictionDefinition(wc, predictionId = 13242)
#' }
#' @export
getPredictionDefinition <- function(wc, predictionId) {
  result <- getDefinition(wc = wc, id = predictionId, category = "prediction")
  return(result)
}


#' Delete Prediction id definition. \lifecycle{stable}
#' @details
#' Delete the Prediction definition from WebAPI for a given Prediction id
#'
#' @template WebApiConnection
#' @param predictionId   An integer id representing the id that uniquely identifies a Prediction
#'                       definition in a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deletePredictionDefinition(wc, predictionId = 13242)
#' }
#' @export
deletePredictionDefinition <- function(wc, predictionId) {
  result <- deleteDefinition(wc = wc, id = predictionId, category = "prediction")
  return(result)
}


#' Check if Prediction definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Prediction definition name.
#'
#' @template WebApiConnection
#' @param predictionName   A string name for the Prediction to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsPredictionName(wc, predictionName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsPredictionName <- function(wc, predictionName) {
  definitionsMetaData <- getPredictionDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == predictionName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Prediction definitions. \lifecycle{stable}
#' @details
#' Detect string matched Prediction definition names from the WebApi, and retrieve metadata
#' definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPredictionDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectPredictions(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectPredictionsByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getPredictionDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Prediction definition. \lifecycle{maturing}
#' @details
#' Post Prediction definition to WebAPI
#'
#' @template WebApiConnection
#' @param name                   A valid name for the definition. WebApi will use this name (if valid)
#'                               as the name of the definition. WebApi checks for validity, such as
#'                               uniqueness, absence of unacceptable character etc. An error might be
#'                               thrown.
#' @param predictionDefinition   An R list object containing the expression for the specification. This
#'                               will be converted to JSON expression by function and posted into the
#'                               WebApi. Note: only limited checks are performed in R to check the
#'                               validity of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postPredictionDefinition(wc, name = "new valid name", predictionDefinition = definition)
#' }
#' @export
postPredictionDefinition <- function(wc, name, predictionDefinition) {
  result <- postDefinition(wc,
                           name = name,
                           category = "prediction",
                           definition = predictionDefinition)
  return(result)
}
#' Get the meta data for Characterization definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for Characterization. This function is useful to retrieve the current
#' Characterization specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for Characterization. Note: modifiedDate and createdDate are
#' returned as text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCharacterizationDefinitionsMetaData(wc)
#' }
#' @export
getCharacterizationDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("characterization"))
  return(metaData)
}


#' is Characterization id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a Characterization is valid. The following checks are performed. 1)
#' checks if all the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param characterizationIds   A list of integer id(s) of the Characterization to be tested for
#'                              validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidCharacterizationId(wc, characterizationIds = c(13242, 3423, 34))
#' }
#' @export
isValidCharacterizationId <- function(wc, characterizationIds) {
  result <- isValidId(wc = wc, category = "characterization", ids = characterizationIds)
  return(result)
}


#' Get Characterization id definition. \lifecycle{stable}
#' @details
#' Obtain the Characterization definition from WebAPI for a given Characterization id
#'
#' @template WebApiConnection
#' @param characterizationId   An integer id representing the id that uniquely identifies a
#'                             Characterization definition in a WebApi instance.
#' @return
#' An R object representing the Characterization definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCharacterizationDefinition(wc, characterizationId = 13242)
#' }
#' @export
getCharacterizationDefinition <- function(wc, characterizationId) {
  result <- getDefinition(wc = wc, id = characterizationId, category = "characterization")
  return(result)
}


#' Delete Characterization id definition. \lifecycle{stable}
#' @details
#' Delete the Characterization definition from WebAPI for a given Characterization id
#'
#' @template WebApiConnection
#' @param characterizationId   An integer id representing the id that uniquely identifies a
#'                             Characterization definition in a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deleteCharacterizationDefinition(wc, characterizationId = 13242)
#' }
#' @export
deleteCharacterizationDefinition <- function(wc, characterizationId) {
  result <- deleteDefinition(wc = wc, id = characterizationId, category = "characterization")
  return(result)
}


#' Check if Characterization definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Characterization definition name.
#'
#' @template WebApiConnection
#' @param characterizationName   A string name for the Characterization to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsCharacterizationName(wc, characterizationName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsCharacterizationName <- function(wc, characterizationName) {
  definitionsMetaData <- getCharacterizationDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == characterizationName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Characterization definitions. \lifecycle{stable}
#' @details
#' Detect string matched Characterization definition names from the WebApi, and retrieve metadata
#' definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from
#' \link[ROhdsiWebApi]{getCharacterizationDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectCharacterizations(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectCharacterizationsByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getCharacterizationDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Characterization definition. \lifecycle{maturing}
#' @details
#' Post Characterization definition to WebAPI
#'
#' @template WebApiConnection
#' @param name                         A valid name for the definition. WebApi will use this name (if
#'                                     valid) as the name of the definition. WebApi checks for
#'                                     validity, such as uniqueness, absence of unacceptable character
#'                                     etc. An error might be thrown.
#' @param characterizationDefinition   An R list object containing the expression for the
#'                                     specification. This will be converted to JSON expression by
#'                                     function and posted into the WebApi. Note: only limited checks
#'                                     are performed in R to check the validity of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postCharacterizationDefinition(wc,
#'                                name = "new valid name",
#'                                characterizationDefinition = definition)
#' }
#' @export
postCharacterizationDefinition <- function(wc, name, characterizationDefinition) {
  result <- postDefinition(wc,
                           name = name,
                           category = "characterization",
                           definition = characterizationDefinition)
  return(result)
}

#' Get generation information for Characterization id.
#'
#' @details
#' Get generation (execution) information about Characterization for a characterizationId.
#'
#' @template WebApiConnection
#' @param characterizationId   An integer id representing the id that uniquely identifies a
#'                             Characterization definition in a WebApi instance.
#' @return
#' An R object representing the Characterization definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCharacterizationGenerationInformation(wc, characterizationId = 13242)
#' }
#' @export
getCharacterizationGenerationInformation <- function(wc, characterizationId) {
  .checkBaseUrl(wc$baseUrl)
  response <- getGenerationInformation(wc = wc,
                                       id = characterizationId,
                                       category = "characterization")
  return(response)
}


#' Invoke generation of Characterization id.
#'
#' @details
#' Invoke the generation of Characterization id in the WebApi.
#'
#' @template WebApiConnection
#' @param characterizationId   An integer id representing the id that uniquely identifies a
#'                             Characterization definition in a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' invokeCharacterizationGeneration(wc, characterizationId = 13242, sourceKey = "HCUP")
#' }
#' @export
invokeCharacterizationGeneration <- function(wc, characterizationId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- invokeGeneration(wc,
                               id = characterizationId,
                               category = "characterization",
                               sourceKey = sourceKey)
  return(response)
}

#' Cancel generation of Characterization id.
#'
#' @details
#' Cancel the generation of Characterization id in the WebApi.
#'
#' @template WebApiConnection
#' @param characterizationId   An integer id representing the id that uniquely identifies a
#'                             Characterization definition in a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' cancelCharacterizationGeneration(wc, characterizationId = 13242, sourceKey = "HCUP")
#' }
#' @export
cancelCharacterizationGeneration <- function(wc, characterizationId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- cancelGeneration(wc,
                               id = characterizationId,
                               category = "characterization",
                               sourceKey = sourceKey)
  return(response)
}


#' Get results for a Characterization Id.
#'
#' @details
#' Get the results for Characterization id.
#'
#' @template WebApiConnection
#' @template CharacterizationId
#' @return
#' An R object with results.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getCharacterizationResults(wc, characterizationId = 342)
#' }
#' @export
# Check name
getCharacterizationResults <- function(wc, characterizationId) {
  result <- getResults(wc = wc, id = characterizationId, category = "characterization")
  return(result)
}
#' Get the meta data for Pathway definitions. \lifecycle{stable}
#' @details
#' Get the meta data of WebApi specifications such as id, name, created/modified details, hash object,
#' etc. from WebApi for Pathway. This function is useful to retrieve the current Pathway
#' specifications.
#'
#' @template WebApiConnection
#' @return
#' A tibble of specification metadata for Pathway. Note: modifiedDate and createdDate are returned as
#' text/character.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getPathwayDefinitionsMetaData(wc)
#' }
#' @export
getPathwayDefinitionsMetaData <- function(wc) {
  metaData <- getDefinitionsMetadata(wc = wc, category = c("pathway"))
  return(metaData)
}


#' is Pathway id a valid definition in the WebApi. \lifecycle{stable}
#' @details
#' Checks if a set of id for a Pathway is valid. The following checks are performed. 1) checks if all
#' the ids exists in the WebApi i.e. valid.
#'
#' @template WebApiConnection
#' @param pathwayIds   A list of integer id(s) of the Pathway to be tested for validity.
#' @return
#' A logical vector indicating if an ID is valid.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' isValidPathwayId(wc, pathwayIds = c(13242, 3423, 34))
#' }
#' @export
isValidPathwayId <- function(wc, pathwayIds) {
  result <- isValidId(wc = wc, category = "pathway", ids = pathwayIds)
  return(result)
}


#' Get Pathway id definition. \lifecycle{stable}
#' @details
#' Obtain the Pathway definition from WebAPI for a given Pathway id
#'
#' @template WebApiConnection
#' @param pathwayId   An integer id representing the id that uniquely identifies a Pathway definition
#'                    in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getPathwayDefinition(wc, pathwayId = 13242)
#' }
#' @export
getPathwayDefinition <- function(wc, pathwayId) {
  result <- getDefinition(wc = wc, id = pathwayId, category = "pathway")
  return(result)
}


#' Delete Pathway id definition. \lifecycle{stable}
#' @details
#' Delete the Pathway definition from WebAPI for a given Pathway id
#'
#' @template WebApiConnection
#' @param pathwayId   An integer id representing the id that uniquely identifies a Pathway definition
#'                    in a WebApi instance.
#' @return
#' None, unless error.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' deletePathwayDefinition(wc, pathwayId = 13242)
#' }
#' @export
deletePathwayDefinition <- function(wc, pathwayId) {
  result <- deleteDefinition(wc = wc, id = pathwayId, category = "pathway")
  return(result)
}


#' Check if Pathway definition name exists. \lifecycle{stable}
#' @details
#' Check if a string name already exists in the WebApi as a Pathway definition name.
#'
#' @template WebApiConnection
#' @param pathwayName   A string name for the Pathway to be checked.
#' @return
#' If found, the function will return a tibble with details of the specification. If not found, FALSE
#' will be returned.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' existsPathwayName(wc, pathwayName = "this text string needs to be checked")
#' }
#' @export
# Check name
existsPathwayName <- function(wc, pathwayName) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(.data$name == pathwayName)
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    FALSE
  }
}


#' Detect the presence of string matched Pathway definitions. \lifecycle{stable}
#' @details
#' Detect string matched Pathway definition names from the WebApi, and retrieve metadata definitions.
#'
#' @template WebApiConnection
#' @param pattern   A pattern to look for. See \link[stringr]{str_detect} for details.
#' @param negate    If TRUE, return non-matching elements. See \link[stringr]{str_detect} for details.
#' @return
#' FALSE if no matches. If matched - output from \link[ROhdsiWebApi]{getPathwayDefinitionsMetaData}
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' detectPathways(wc, pattern = "this text string to search in pattern")
#' }
#' @export
# Check name
detectPathwaysByName <- function(wc, pattern, negate = FALSE) {
  definitionsMetaData <- getPathwayDefinitionsMetaData(wc = wc)
  matched <- definitionsMetaData %>% dplyr::filter(stringr::str_detect(string = .data$name,
                                                                       pattern = pattern,
                                                                       negate = negate))
  if (nrow(matched) > 0) {
    return(matched)
  } else {
    return(FALSE)
  }
}




#' Post Pathway definition. \lifecycle{maturing}
#' @details
#' Post Pathway definition to WebAPI
#'
#' @template WebApiConnection
#' @param name                A valid name for the definition. WebApi will use this name (if valid) as
#'                            the name of the definition. WebApi checks for validity, such as
#'                            uniqueness, absence of unacceptable character etc. An error might be
#'                            thrown.
#' @param pathwayDefinition   An R list object containing the expression for the specification. This
#'                            will be converted to JSON expression by function and posted into the
#'                            WebApi. Note: only limited checks are performed in R to check the
#'                            validity of this expression.
#' @return
#' This function will return a dataframe object with one row describing the posted WebApi expression
#' and its details. If unsuccessful a STOP message will be shown.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' postPathwayDefinition(wc, name = "new valid name", pathwayDefinition = definition)
#' }
#' @export
postPathwayDefinition <- function(wc, name, pathwayDefinition) {
  result <- postDefinition(wc, name = name, category = "pathway", definition = pathwayDefinition)
  return(result)
}

#' Get generation information for Pathway id.
#'
#' @details
#' Get generation (execution) information about Pathway for a pathwayId.
#'
#' @template WebApiConnection
#' @param pathwayId   An integer id representing the id that uniquely identifies a Pathway definition
#'                    in a WebApi instance.
#' @return
#' An R object representing the Pathway definition
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getPathwayGenerationInformation(wc, pathwayId = 13242)
#' }
#' @export
getPathwayGenerationInformation <- function(wc, pathwayId) {
  .checkBaseUrl(wc$baseUrl)
  response <- getGenerationInformation(wc = wc, id = pathwayId, category = "pathway")
  return(response)
}


#' Invoke generation of Pathway id.
#'
#' @details
#' Invoke the generation of Pathway id in the WebApi.
#'
#' @template WebApiConnection
#' @param pathwayId   An integer id representing the id that uniquely identifies a Pathway definition
#'                    in a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' invokePathwayGeneration(wc, pathwayId = 13242, sourceKey = "HCUP")
#' }
#' @export
invokePathwayGeneration <- function(wc, pathwayId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- invokeGeneration(wc, id = pathwayId, category = "pathway", sourceKey = sourceKey)
  return(response)
}

#' Cancel generation of Pathway id.
#'
#' @details
#' Cancel the generation of Pathway id in the WebApi.
#'
#' @template WebApiConnection
#' @param pathwayId   An integer id representing the id that uniquely identifies a Pathway definition
#'                    in a WebApi instance.
#' @template SourceKey
#' @return
#' A tibble with job status information.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' cancelPathwayGeneration(wc, pathwayId = 13242, sourceKey = "HCUP")
#' }
#' @export
cancelPathwayGeneration <- function(wc, pathwayId, sourceKey) {
  .checkBaseUrl(wc$baseUrl)
  response <- cancelGeneration(wc, id = pathwayId, category = "pathway", sourceKey = sourceKey)
  return(response)
}


#' Get results for a Pathway Id.
#'
#' @details
#' Get the results for Pathway id.
#'
#' @template WebApiConnection
#' @template PathwayId
#' @return
#' An R object with results.
#'
#' @examples
#' \dontrun{
#' wc <- connectWebApi(baseUrl = "http://server.org:80/WebAPI")
#' getPathwayResults(wc, pathwayId = 342)
#' }
#' @export
# Check name
getPathwayResults <- function(wc, pathwayId) {
  result <- getResults(wc = wc, id = pathwayId, category = "pathway")
  return(result)
}
