# Copyright 2020 Observational Health Data Sciences and Informatics
#
# This file is part of ROhdsiWebApi
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Format and check code
OhdsiRTools::formatRFolder("R")
OhdsiRTools::checkUsagePackage("ROhdsiWebApi")
OhdsiRTools::updateCopyrightYearFolder()
devtools::spell_check()

# Create manual and vignette
unlink("extras/ROhdsiWebApi.pdf")
shell("R CMD Rd2pdf ./ --output=extras/ROhdsiWebApi.pdf")

dir.create("inst/doc", recursive = TRUE)
rmarkdown::render("vignettes/WorkingWithCohorts.Rmd",
                  output_file = "../inst/doc/WorkingWithCohorts.pdf",
                  rmarkdown::pdf_document(latex_engine = "pdflatex",
                                          toc = TRUE,
                                          number_sections = TRUE))
unlink("inst/doc/WorkingWithCohorts.tex")

pkgdown::build_site()


# Generate functions from template ----------------------
webApiCategories <- tidyr::tibble(category =  c('conceptSet','cohort','incidenceRate',
                                                'estimation','prediction','characterization',
                                                'pathway')
) %>% 
  dplyr::mutate(categoryFirstUpper = paste0(toupper(substr(category, 1, 1)), substr(category, 2, nchar(category)))
                )



arguments <- tidyr::tibble(functionNameDefinitionsMetaData = paste0("get", webApiCategories$categoryFirstUpper, "DefinitionsMetaData"),
                           functionNameIsValid = paste0("isValid", webApiCategories$categoryFirstUpper, "Id"),
                           categoriesFirstUpper = webApiCategories$categoryFirstUpper,
                           categories = webApiCategories$category,
                           description = paste0("Retrieve meta data information for all ", 
                                                webApiCategories$categoryFirstUpper, 
                                                "(s) in WebApi"
                                                ),
                           example = paste0(functionNameDefinitionsMetaData, "(baseUrl")
                           )



writeLines(text = readLines("extras/templateAutogeneratedFunctionScripts.R"), 
           con = "R/AutoGeneratedDefinitions.R"
           )
for (i in (1:nrow(arguments))) { #i = 1
  argument <- arguments %>% dplyr::slice(i)
  
  code <- readLines("extras/templateWebApiFunctions.R")
  code <- stringr::str_replace(string = code, pattern = "%category%", replacement = argument$categories)
  code <- stringr::str_replace(string = code, pattern = "%categoryFirstUpper%", replacement = argument$categoriesFirstUpper)
  code <- stringr::str_replace(string = code, pattern = "%functionNameDefinitionsMetaData%", replacement = argument$functionNameDefinitionsMetaData)
  code <- stringr::str_replace(string = code, pattern = "%functionNameIsValid%", replacement = argument$functionNameIsValid)
  
  sink(file = "R/AutoGeneratedDefinitions.R",
       append = TRUE,
       type = "output"
       )
  writeLines(code)
  sink()
}


OhdsiRTools::formatRFile("R/AutoGeneratedDefinitions.R")
